name: master-koehler
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.7
  - absl-py
  - appdirs
  - cachetools
  - certifi
  - charset-normalizer
  - click
  - cloudpickle
  - colorama
  - commonmark
  - cycler
  - decorator
  - filelock
  - fonttools
  - gitdb
  - gitpython
  - google-auth-oauthlib
  - google-auth
  - grpcio
  - gymnasium
  - idna
  - imageio-ffmpeg
  - imageio
  - importlib-metadata
  - importlib-resources
  - jax-jumpy
  - kiwisolver
  - markdown
  - markupsafe
  - matplotlib
  - moviepy
  - numpy
  - oauthlib
  - packaging
  - pandas
  - pathtools
  - pillow
  - protobuf
  - psutil
  - pyasn1-modules
  - pyasn1
  - pygments
  - pyparsing
  - python-dateutil
  - pytz
  - pyyaml
  - requests-oauthlib
  - rich
  - rsa
  - setproctitle
  - setuptools
  - six
  - smmap
  - tenacity
  - tensorboard
  - tqdm
  - typing-extensions
  - urllib3
  - wandb
  - werkzeug
  - wheel
  - zipp
  - pip
  - pip:
      - stable-baselines3
      - gym
      - ale-py
      - requests
      - autorom-accept-rom-license
      - huggingface-hub
      - sentry-sdk
      - torch==1.12.1
      - opencv-python
      - autorom[accept-rom-license]
      - docker-pycreds
      - farama-notifications
      - tensorboard-data-server
      - tensorboard-plugin-wit

